---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        args: [--skipslow]
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/rubik/xenon
    rev: v0.9.0
    hooks:
      - id: xenon
        args: [ --max-absolute B, --max-modules A, --max-average A ]
-   repo: local
    hooks:
    -   id: coverage
        name: coverage
        entry: coverage report
        args: [--fail-under=80]
        language: system
        pass_filenames: false
        always_run: true
